In [2]:
import data_processing as dp
import model
import pandas as pd

df = dp.ingest('data/bank-additional.csv')
df = dp.ordinal_encoding(df, 'y', ['no', 'yes'])
df = dp.nominal_encoding(df)
df

/Users/vishwasgowda/Desktop/Projects/ML/bank_marketing/bank/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_oct,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success
0,30,487,2,999,0,-1.8,92.893,-46.2,1.313,5099.1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,39,346,4,999,0,1.1,93.994,-36.4,4.855,5191.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,25,227,1,999,0,1.4,94.465,-41.8,4.962,5228.1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,38,17,3,999,0,1.4,94.465,-41.8,4.959,5228.1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,47,58,1,999,0,-0.1,93.200,-42.0,4.191,5195.8,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4114,30,53,1,999,0,1.4,93.918,-42.7,4.958,5228.1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4115,39,219,1,999,0,1.4,93.918,-42.7,4.959,5228.1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4116,27,64,2,999,1,-1.8,92.893,-46.2,1.354,5099.1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4117,58,528,1,999,0,1.4,93.444,-36.1,4.966,5228.1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4118,34,175,1,999,0,-0.1,93.200,-42.0,4.120,5195.8,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [3]:
df = dp.outlier_detection(df)
df

/Users/vishwasgowda/Desktop/Projects/ML/bank_marketing/bank/lib/python3.11/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/Users/vishwasgowda/Desktop/Projects/ML/bank_marketing/data_processing.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('is_inliner', axis=1, inplace=True)

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_oct,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success
0,30,487,2,999,0,-1.8,92.893,-46.2,1.313,5099.1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,39,346,4,999,0,1.1,93.994,-36.4,4.855,5191.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,25,227,1,999,0,1.4,94.465,-41.8,4.962,5228.1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,47,58,1,999,0,-0.1,93.200,-42.0,4.191,5195.8,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
6,32,290,4,999,0,-1.1,94.199,-37.5,0.879,4963.6,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4114,30,53,1,999,0,1.4,93.918,-42.7,4.958,5228.1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4115,39,219,1,999,0,1.4,93.918,-42.7,4.959,5228.1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4116,27,64,2,999,1,-1.8,92.893,-46.2,1.354,5099.1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4117,58,528,1,999,0,1.4,93.444,-36.1,4.966,5228.1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4118,34,175,1,999,0,-0.1,93.200,-42.0,4.120,5195.8,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [4]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X = df.drop('target_encoded', axis=1)
y = df['target_encoded']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
pca = PCA(n_components=0.85)
X_pca = pca.fit_transform(X_scaled)
X_pca = pd.DataFrame(X_pca)
y = y.reset_index(drop=True)
df = pd.concat([X_pca, y],axis=1, join='inner')

In [5]:
df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,target_encoded
0,2.362074,1.470039,0.441633,1.520508,-1.641380,-1.065624,0.150034,0.390391,-1.141347,-0.911345,...,-0.568474,0.107667,-0.573991,0.060431,0.738714,0.344006,0.224462,0.015576,-0.361662,0
1,-1.549877,0.573138,-3.410800,0.208847,0.063588,0.108842,-0.882114,1.101050,0.235559,0.808586,...,-0.895983,1.209265,-0.191432,0.307348,0.144694,0.327906,-0.024191,0.159230,0.257426,0
2,-2.355207,0.742339,-1.831391,0.907496,0.385618,-0.737358,0.782288,-0.189488,-0.403835,-0.373098,...,0.672292,-1.151802,-0.398247,0.012279,-0.168192,-0.172165,-0.374906,0.286748,0.790820,0
3,0.914082,-1.836789,1.182471,-0.810971,-0.955504,0.348837,0.539104,-0.350276,0.329440,-0.136489,...,0.391929,0.062351,0.505980,0.197659,0.099709,0.082185,-1.169788,0.641136,-1.583918,0
4,2.806884,-1.767765,-2.125613,0.292358,-3.223884,0.878356,0.597292,0.076083,-1.228277,1.406282,...,-6.686914,-2.292819,0.953884,1.695459,-2.747924,6.014440,-3.858811,1.074051,1.567524,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3702,-0.996163,-1.754557,1.839770,2.200369,0.188324,-2.170293,0.926515,-1.038025,2.110224,-0.690487,...,0.476494,1.553268,0.870252,-1.159454,-0.344648,-0.029891,-0.165434,0.097239,0.302724,0
3703,-1.791339,-0.465957,-0.581370,0.132726,0.240000,-0.797515,0.644898,-0.064089,-0.045678,0.180980,...,-0.526343,0.204700,0.083357,-0.328189,0.711965,0.415585,-0.224218,0.110719,-0.644359,0
3704,5.857167,1.672363,-3.541175,-0.262264,2.832429,-1.123075,-0.930276,-0.163315,0.513262,2.255137,...,-0.592097,1.731605,0.717432,0.946930,0.108542,0.690355,1.341345,-0.745431,0.197613,0
3705,-0.750934,-1.595330,0.831358,-1.780411,0.113803,1.373188,-1.230884,1.178736,0.835277,0.671154,...,0.328884,-0.025657,-1.010121,-0.351540,0.591530,0.988056,-0.285795,-0.277615,0.220822,0
3706,1.234862,-2.001598,-0.464535,0.145732,-0.102499,-1.325059,0.451963,-0.171773,-0.110352,-0.031261,...,-0.585497,0.645146,-0.636128,1.234790,0.047599,-0.243206,-0.569475,0.566142,-1.372671,0

In [6]:
df.to_csv('data/small-data-proc.csv', index=False)